#!/bin/bash
#SBATCH -J JOB_NAME
#SBATCH -n 128
#SBATCH --mem=128G
#SBATCH --exclusive
#SBATCH -t 4-00:00:00
#SBATCH --mail-type=ALL
#SBATCH -p thin

module load 2022
module load OpenMPI/4.1.4-GCC-11.3.0

lmp=~/software/lammps/lammps2018/src/
srun $lmp/lmp_mpi < simulation.in

wait
exit 0 
